/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v5.0.0), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2021 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 103 }

  /* === schema: public === */

  /* --- enums --- */


  /* --- tables --- */

  /**
   * **User**
   * - Table in database
   */
  export namespace User {
    export type Table = 'User';
    export interface Selectable {
      /**
      * **User.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"User_id_seq"'::regclass)`
      */
      id: number;
      /**
      * **User.username**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      username: string;
      /**
      * **User.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      createdAt: Date | null;
    }
    export interface JSONSelectable {
      /**
      * **User.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"User_id_seq"'::regclass)`
      */
      id: number;
      /**
      * **User.username**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      username: string;
      /**
      * **User.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      createdAt: db.TimestampTzString | null;
    }
    export interface Whereable {
      /**
      * **User.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"User_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.username**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      username?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **User.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"User_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **User.username**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      username: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **User.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **User.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('"User_id_seq"'::regclass)`
      */
      id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **User.username**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      username?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **User.password**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      password?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **User.createdAt**
      * - `timestamptz` in database
      * - Nullable, default: `now()`
      */
      createdAt?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'User_pkey' | 'User_username_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = db.GenericSQLExpression | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Table | Whereable | Column;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* === cross-table types === */

  export type Table = User.Table;
  export type Selectable = User.Selectable;
  export type JSONSelectable = User.JSONSelectable;
  export type Whereable = User.Whereable;
  export type Insertable = User.Insertable;
  export type Updatable = User.Updatable;
  export type UniqueIndex = User.UniqueIndex;
  export type Column = User.Column;
  export type AllBaseTables = [User.Table];
  export type AllForeignTables = [];
  export type AllViews = [];
  export type AllMaterializedViews = [];
  export type AllTablesAndViews = [User.Table];


  export type SelectableForTable<T extends Table> = {
    User: User.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    User: User.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    User: User.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    User: User.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    User: User.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    User: User.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    User: User.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    User: User.SQL;
  }[T];

}
